name: 构建和发布

on:
  push: 
    branches: ["master"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV_STATE: github
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          # cache: 'pnpm'                     

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.17.1                      

      - name: Change depends
        run: sh ./script/install.sh
      
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Prepare tag/name/body variables
        id: vars
        shell: bash
        run: |
          # Determine TAG:
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="release-${GITHUB_RUN_NUMBER}-$(echo ${GITHUB_SHA} | cut -c1-7)"
          fi

          # Name and body
          NAME="Release $TAG"
            # Use the latest commit's subject and link as release body
            COMMIT_SHA="${GITHUB_SHA}"
            SHORT_SHA="${COMMIT_SHA:0:7}"
            COMMIT_SUBJECT="$(git --no-pager log -1 --pretty=format:'%s' "$COMMIT_SHA" 2>/dev/null || echo 'No commit message')"
            BODY="Commit ${SHORT_SHA} — ${COMMIT_SUBJECT} (${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${COMMIT_SHA})"
          # expose outputs
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "name=$NAME" >> "$GITHUB_OUTPUT"
          echo "body=$BODY" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
           ./dist/delta-comic-plugin-cosav.user.js
          tag_name: ${{ steps.vars.outputs.tag }}
          name: ${{ steps.vars.outputs.name }}
          body: ${{ steps.vars.outputs.body }}
          repository: wenxig/delta-comic
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
